-- Gradebook schema (PostgreSQL)
-- Based on: /root/MLDevOps/EduAPI_DB (2).sql
-- Adjustments for Postgres + requested field:
--  - users.phone_number added
--  - timetable.day_of_week uses SMALLINT (1=Mon..7=Sun) instead of BLOB
--  - absences.timetable_id is nullable because FK uses ON DELETE SET NULL

CREATE TABLE IF NOT EXISTS "roles" (
	"role_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY("role_id")
);

CREATE TABLE IF NOT EXISTS "users" (
	"user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"role_id" INTEGER NOT NULL,
	"username" VARCHAR(100) NOT NULL UNIQUE,
	"email" VARCHAR(150) NOT NULL UNIQUE,
	"password_hash" VARCHAR(255) NOT NULL,
	"first_name" VARCHAR(50) NOT NULL,
	"last_name" VARCHAR(50) NOT NULL,
	"phone_number" VARCHAR(30),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "grade_levels" (
	"grade_level_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"numeric_level" INTEGER NOT NULL UNIQUE,
	"name" VARCHAR(50),
	PRIMARY KEY("grade_level_id")
);

CREATE TABLE IF NOT EXISTS "subjects" (
	"subject_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL UNIQUE,
	"code" VARCHAR(20) UNIQUE,
	PRIMARY KEY("subject_id")
);

CREATE TABLE IF NOT EXISTS "curriculum_reqs" (
	"req_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"grade_level_id" INTEGER NOT NULL,
	"subject_id" INTEGER NOT NULL,
	"required_hours_per_week" INTEGER DEFAULT 1,
	PRIMARY KEY("req_id")
);

CREATE TABLE IF NOT EXISTS "teachers" (
	"user_id" INTEGER,
	"specialization" VARCHAR(100),
	"hire_date" DATE DEFAULT CURRENT_DATE,
	PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "classes" (
	"class_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(20) NOT NULL UNIQUE,
	"grade_level_id" INTEGER NOT NULL,
	"homeroom_teacher_id" INTEGER,
	"academic_year" VARCHAR(9) DEFAULT '2025-2026',
	PRIMARY KEY("class_id")
);

CREATE TABLE IF NOT EXISTS "students" (
	"user_id" INTEGER,
	"class_id" INTEGER,
	"date_of_birth" DATE,
	PRIMARY KEY("user_id")
);

CREATE TABLE IF NOT EXISTS "class_courses" (
	"course_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"class_id" INTEGER NOT NULL,
	"subject_id" INTEGER NOT NULL,
	"teacher_id" INTEGER NOT NULL,
	PRIMARY KEY("course_id")
);

CREATE TABLE IF NOT EXISTS "timetable" (
	"timetable_id" INTEGER GENERATED BY DEFAULT AS IDENTITY,
	"class_course_id" INTEGER NOT NULL,
	"day_of_week" SMALLINT NOT NULL,
	"start_time" TIME NOT NULL,
	"end_time" TIME NOT NULL,
	"room" VARCHAR(20),
	PRIMARY KEY("timetable_id"),
	CONSTRAINT "timetable_day_of_week_valid" CHECK ("day_of_week" BETWEEN 1 AND 7)
);

CREATE TABLE IF NOT EXISTS "grades" (
	"grade_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"student_id" INTEGER NOT NULL,
	"subject_id" INTEGER NOT NULL,
	"grade_value" INTEGER NOT NULL,
	"grade_date" DATE NOT NULL DEFAULT CURRENT_DATE,
	"comments" VARCHAR(255),
	PRIMARY KEY("grade_id"),
	CONSTRAINT "grades_grade_value_valid" CHECK ("grade_value" BETWEEN 1 AND 10)
);

CREATE TABLE IF NOT EXISTS "absences" (
	"absence_id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"student_id" INTEGER NOT NULL,
	"subject_id" INTEGER NOT NULL,
	"timetable_id" INTEGER,
	"absence_date" DATE NOT NULL,
	"is_excused" BOOLEAN NOT NULL DEFAULT false,
	"reason" VARCHAR(255),
	PRIMARY KEY("absence_id")
);

ALTER TABLE "users"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("role_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "curriculum_reqs"
ADD FOREIGN KEY("grade_level_id") REFERENCES "grade_levels"("grade_level_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "curriculum_reqs"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "teachers"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "classes"
ADD FOREIGN KEY("grade_level_id") REFERENCES "grade_levels"("grade_level_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "classes"
ADD FOREIGN KEY("homeroom_teacher_id") REFERENCES "teachers"("user_id")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "students"
ADD FOREIGN KEY("user_id") REFERENCES "users"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "students"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("class_id")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "class_courses"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("class_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "class_courses"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "class_courses"
ADD FOREIGN KEY("teacher_id") REFERENCES "teachers"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "timetable"
ADD FOREIGN KEY("class_course_id") REFERENCES "class_courses"("course_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "grades"
ADD FOREIGN KEY("student_id") REFERENCES "students"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "absences"
ADD FOREIGN KEY("student_id") REFERENCES "students"("user_id")
ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE "absences"
ADD FOREIGN KEY("timetable_id") REFERENCES "timetable"("timetable_id")
ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE "absences"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "grades"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("subject_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
